runtime: php
env: flex

runtime_config:
  document_root: public

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:RYFsv5DDBJGzm46y4g6TG45N9KRaPIr+gjGnLS8/FnQ=
